package cli

import (
	"fmt"
	"sort"
	"strings"
	"unicode"
)

type Shell string

const (
	ShellFish       Shell = "fish"
	ShellNushell    Shell = "nushell"
	ShellBash       Shell = "bash"
	ShellZsh        Shell = "zsh"
	ShellPowerShell Shell = "powershell"
)

type AdapterCapabilities struct {
	Descriptions    bool `json:"descriptions"`
	StaticMetadata  bool `json:"static_metadata"`
	FileDirectives  bool `json:"file_directives"`
	TypedSignatures bool `json:"typed_signatures"`
	DynamicProtocol bool `json:"dynamic_protocol"`
}

type ShellAdapter interface {
	Shell() Shell
	Capabilities() AdapterCapabilities
	Generate(Schema) (string, error)
}

func SupportedShells() []Shell {
	return []Shell{ShellFish, ShellNushell, ShellBash, ShellZsh, ShellPowerShell}
}

func (c *CompiledApp) CompletionScript(shell Shell) (string, error) {
	adapter, err := shellAdapter(shell)
	if err != nil {
		return "", err
	}
	// Completion integrations are deliberately spec-agnostic. Installed scripts
	// carry only the executable name and protocol adapter; commands, flags,
	// aliases, values and availability always come from the runtime planner.
	return adapter.Generate(Schema{Name: c.graph.Name})
}

func ShellCapabilities(shell Shell) (AdapterCapabilities, error) {
	adapter, err := shellAdapter(shell)
	if err != nil {
		return AdapterCapabilities{}, err
	}
	return adapter.Capabilities(), nil
}

func shellAdapter(shell Shell) (ShellAdapter, error) {
	switch shell {
	case ShellFish:
		return fishAdapter{}, nil
	case ShellNushell:
		return nushellAdapter{}, nil
	case ShellBash:
		return bashAdapter{}, nil
	case ShellZsh:
		return zshAdapter{}, nil
	case ShellPowerShell:
		return powershellAdapter{}, nil
	default:
		return nil, fmt.Errorf("cli: unsupported shell %q", shell)
	}
}

type bashAdapter struct{}

func (bashAdapter) Shell() Shell { return ShellBash }
func (bashAdapter) Capabilities() AdapterCapabilities {
	return AdapterCapabilities{Descriptions: false, StaticMetadata: false, FileDirectives: true, DynamicProtocol: true}
}
func (bashAdapter) Generate(s Schema) (string, error) {
	fn := "_" + shellIdentifier(s.Name) + "_completion"
	tool := shSingleQuote(s.Name)
	return fmt.Sprintf(`# generated by %s; completion protocol %d
%s() {
  local cur="$2" base="$2" attach=""
  local tag value label description kind group id
  local files=0 directories=0 executables=0 nospace=0 keeporder=0
  local magic protocol
  local -a values=()
  if [[ "$cur" == --*=* ]]; then attach="${cur%%%%=*}="; base="${cur#*=}"; fi
  exec 3< <(command %s __cli complete-shell %d bash "$COMP_CWORD" "${#cur}" -- "${COMP_WORDS[@]}" 2>/dev/null)
  IFS= read -r -d '' magic <&3 || { exec 3<&-; return 0; }
  IFS= read -r -d '' protocol <&3 || { exec 3<&-; return 0; }
  [[ "$magic" == cli-completion && "$protocol" == %d ]] || { exec 3<&-; return 0; }
  while IFS= read -r -d '' tag <&3; do
    case "$tag" in
      candidate)
        IFS= read -r -d '' value <&3 || break
        IFS= read -r -d '' label <&3 || break
        IFS= read -r -d '' description <&3 || break
        IFS= read -r -d '' kind <&3 || break
        IFS= read -r -d '' group <&3 || break
        IFS= read -r -d '' id <&3 || break
        values+=("$value")
        ;;
      directive)
        IFS= read -r -d '' files <&3 || break
        IFS= read -r -d '' directories <&3 || break
        IFS= read -r -d '' executables <&3 || break
        IFS= read -r -d '' nospace <&3 || break
        IFS= read -r -d '' keeporder <&3 || break
        ;;
      end) break ;;
      *) break ;;
    esac
  done
  exec 3<&-
  COMPREPLY=("${values[@]}")
  local item
  if [[ "$directories" == 1 ]]; then
    while IFS= read -r item; do COMPREPLY+=("$attach$item"); done < <(compgen -d -- "$base")
  elif [[ "$files" == 1 ]]; then
    while IFS= read -r item; do COMPREPLY+=("$attach$item"); done < <(compgen -f -- "$base")
  fi
  if [[ "$executables" == 1 ]]; then
    while IFS= read -r item; do COMPREPLY+=("$attach$item"); done < <(compgen -c -- "$base")
  fi
  [[ "$nospace" == 1 ]] && compopt -o nospace 2>/dev/null || true
}
complete -F %s -- %s
`, s.Name, CompletionProtocol, fn, tool, CompletionProtocol, CompletionProtocol, fn, tool), nil
}

type zshAdapter struct{}

func (zshAdapter) Shell() Shell { return ShellZsh }
func (zshAdapter) Capabilities() AdapterCapabilities {
	return AdapterCapabilities{Descriptions: true, StaticMetadata: false, FileDirectives: true, DynamicProtocol: true}
}
func (zshAdapter) Generate(s Schema) (string, error) {
	fn := "_" + shellIdentifier(s.Name)
	tool := shSingleQuote(s.Name)
	return fmt.Sprintf(`#compdef %s
# generated by %s; completion protocol %d
%s() {
  local cur="$PREFIX" tag value label description kind group id
  local magic protocol files=0 directories=0 executables=0 nospace=0 keeporder=0
  local -a values descriptions suffix
  exec 3< <(command %s __cli complete-shell %d zsh "$((CURRENT-1))" "${#cur}" -- "${words[@]}" 2>/dev/null)
  IFS= read -r -d $'\0' magic <&3 || { exec 3<&-; return 0; }
  IFS= read -r -d $'\0' protocol <&3 || { exec 3<&-; return 0; }
  [[ "$magic" == cli-completion && "$protocol" == %d ]] || { exec 3<&-; return 0; }
  while IFS= read -r -d $'\0' tag <&3; do
    case "$tag" in
      candidate)
        IFS= read -r -d $'\0' value <&3 || break
        IFS= read -r -d $'\0' label <&3 || break
        IFS= read -r -d $'\0' description <&3 || break
        IFS= read -r -d $'\0' kind <&3 || break
        IFS= read -r -d $'\0' group <&3 || break
        IFS= read -r -d $'\0' id <&3 || break
        values+=("$value"); descriptions+=("$description") ;;
      directive)
        IFS= read -r -d $'\0' files <&3 || break
        IFS= read -r -d $'\0' directories <&3 || break
        IFS= read -r -d $'\0' executables <&3 || break
        IFS= read -r -d $'\0' nospace <&3 || break
        IFS= read -r -d $'\0' keeporder <&3 || break ;;
      end) break ;;
      *) break ;;
    esac
  done
  exec 3<&-
  [[ "$nospace" == 1 ]] && suffix=(-S '')
  (( ${#values[@]} )) && compadd -Q -d descriptions "${suffix[@]}" -- "${values[@]}"
  if [[ "$cur" == --*=* && ( "$directories" == 1 || "$files" == 1 || "$executables" == 1 ) ]]; then
    compset -P '*='
  fi
  [[ "$directories" == 1 ]] && _directories
  [[ "$files" == 1 && "$directories" != 1 ]] && _files
  [[ "$executables" == 1 ]] && _command_names
  return 0
}
compdef %s %s
`, s.Name, s.Name, CompletionProtocol, fn, tool, CompletionProtocol, CompletionProtocol, fn, tool), nil
}

type powershellAdapter struct{}

func (powershellAdapter) Shell() Shell { return ShellPowerShell }
func (powershellAdapter) Capabilities() AdapterCapabilities {
	return AdapterCapabilities{Descriptions: true, StaticMetadata: false, FileDirectives: false, DynamicProtocol: true}
}
func (powershellAdapter) Generate(s Schema) (string, error) {
	tool := psSingleQuote(s.Name)
	return fmt.Sprintf(`# generated by %s; completion protocol %d
Register-ArgumentCompleter -Native -CommandName %s -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $elements = @($commandAst.CommandElements)
  $argv = @()
  foreach ($element in $elements) {
    if ($element -is [System.Management.Automation.Language.StringConstantExpressionAst]) {
      $argv += $element.Value
    } else {
      $argv += $element.Extent.Text
    }
  }
  if ($argv.Count -eq 0) { $argv = @(%s) }
  # Native completers can be invoked with the cursor in the middle of a command.
  # Derive the logical argv index from AST extents instead of assuming the last token.
  $cursorArg = $argv.Count
  for ($i = 0; $i -lt $elements.Count; $i++) {
    $extent = $elements[$i].Extent
    if ($cursorPosition -lt $extent.StartOffset -or $cursorPosition -le $extent.EndOffset) {
      $cursorArg = $i
      break
    }
  }
  # Protocol offsets count Unicode scalar values rather than UTF-16 code units.
  $cursorOffset = 0
  for ($i = 0; $i -lt $wordToComplete.Length; $i++) {
    if ([char]::IsHighSurrogate($wordToComplete[$i]) -and ($i + 1) -lt $wordToComplete.Length -and [char]::IsLowSurrogate($wordToComplete[$i + 1])) { $i++ }
    $cursorOffset++
  }
  $request = [ordered]@{
    protocol = %d
    argv = $argv
    cursor_arg = $cursorArg
    cursor_offset = $cursorOffset
    shell = 'powershell'
  } | ConvertTo-Json -Compress
  try {
    $result = $request | & %s __cli complete 2>$null | ConvertFrom-Json
  } catch { return }
  if ($result.protocol -ne %d) { return }
  foreach ($candidate in $result.candidates) {
    $tip = if ($candidate.description) { $candidate.description } else { $candidate.value }
    [System.Management.Automation.CompletionResult]::new($candidate.value, $candidate.value, 'ParameterValue', $tip)
  }
}
`, s.Name, CompletionProtocol, tool, tool, CompletionProtocol, tool, CompletionProtocol), nil
}

type fishAdapter struct{}

func (fishAdapter) Shell() Shell { return ShellFish }
func (fishAdapter) Capabilities() AdapterCapabilities {
	return AdapterCapabilities{Descriptions: true, StaticMetadata: false, FileDirectives: true, DynamicProtocol: true}
}
func (fishAdapter) Generate(s Schema) (string, error) {
	fn := "__" + shellIdentifier(s.Name) + "_dynamic_complete"
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by %s; completion protocol %d\n", s.Name, CompletionProtocol)
	fmt.Fprintf(&b, `function %s
    set -l tokens (commandline -opc)
    set -l current (commandline -ct)
    set -l native_prefix "$current"
    set -l native_attach ""
    if string match -q -- '--*=*' "$current"
        set native_attach (string replace -r '=.*$' '=' -- "$current")
        set native_prefix (string replace -r '^[^=]*=' '' -- "$current")
    end
    set -a tokens "$current"
    set -l cursor (math (count $tokens) - 1)
    set -l offset (string length -- "$current")
    command %s __cli complete-shell %d fish $cursor $offset -- $tokens 2>/dev/null | while read -z tag
        switch $tag
            case cli-completion
                read -z protocol
                if test "$protocol" != %d
                    return
                end
            case candidate
                read -z value; read -z label; read -z description; read -z kind; read -z group; read -z id
                set -l safe_value (string escape -- "$value")
                set -l safe_desc (string replace -a \t ' ' -- "$description")
                printf '%%s\t%%s\n' "$safe_value" "$safe_desc"
            case directive
                read -z files; read -z directories; read -z executables; read -z nospace; read -z keeporder
                if test "$directories" = 1
                    __fish_complete_directories "$native_prefix" "" | while read -l native
                        printf '%%s%%s\n' "$native_attach" "$native"
                    end
                else if test "$files" = 1
                    __fish_complete_path "$native_prefix" "" | while read -l native
                        printf '%%s%%s\n' "$native_attach" "$native"
                    end
                end
                if test "$executables" = 1
                    __fish_complete_command "$native_prefix" | while read -l native
                        printf '%%s%%s\n' "$native_attach" "$native"
                    end
                end
            case end
                return
        end
    end
end
`, fn, fishQuote(s.Name), CompletionProtocol, CompletionProtocol)
	fmt.Fprintf(&b, "complete -c %s -f -a '(%s)'\n", fishQuote(s.Name), fn)
	return b.String(), nil
}

type nushellAdapter struct{}

func (nushellAdapter) Shell() Shell { return ShellNushell }
func (nushellAdapter) Capabilities() AdapterCapabilities {
	return AdapterCapabilities{Descriptions: true, StaticMetadata: false, FileDirectives: true, TypedSignatures: false, DynamicProtocol: true}
}
func (nushellAdapter) Generate(s Schema) (string, error) {
	fn := "__" + shellIdentifier(s.Name) + "_complete"
	tool := nuExternal(s.Name)
	return fmt.Sprintf(`# generated by %s; completion protocol %d; requires Nushell 0.114+
def %s [spans: list<string>] {
    let cursor_arg = ([ (($spans | length) - 1) 0] | math max)
    let current = ($spans | last | default "")
    let cursor_offset = ($current | split chars | length)
    let req = {protocol: %d, argv: $spans, cursor_arg: $cursor_arg, cursor_offset: $cursor_offset, shell: "nushell"}
    let result = (try { $req | to json -r | ^%s __cli complete | from json } catch { return [] })
    if $result.protocol != %d { return [] }

    let attach = if ($current | str contains "=") { ($current | split row "=" | first) + "=" } else { "" }
    let native_prefix = if ($attach | is-empty) { $current } else { $current | str replace -r '^[^=]*=' '' }
    let native_paths = if ($result.directive.directories? | default false) {
        $native_prefix | commandline complete --type directory --detailed
    } else if ($result.directive.files? | default false) {
        $native_prefix | commandline complete --type path --detailed
    } else { [] }
    let native_exec = if ($result.directive.executables? | default false) {
        $native_prefix | commandline complete --detailed
    } else { [] }
    let native = ($native_paths | append $native_exec | each {|c|
        if (($c | describe) == "string") {
            {value: $"($attach)($c)", description: ""}
        } else {
            {value: $"($attach)($c.value)", description: ($c.description? | default "")}
        }
    })
    let planned = ($result.candidates | each {|c| {value: $c.value, description: ($c.description? | default "")}})
    ($planned | append $native | uniq-by value)
}

@complete %s
extern %s [...args: string]
`, s.Name, CompletionProtocol, fn, CompletionProtocol, tool, CompletionProtocol, fn, tool), nil
}

func nuExternal(s string) string { return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"` }

func shellIdentifier(s string) string {
	var b strings.Builder
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	if b.Len() == 0 {
		return "cli"
	}
	return b.String()
}
func shSingleQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'" }
func psSingleQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }
func fishQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `'`, `\'`)
	return "'" + s + "'"
}

func sortedShellNames() []string {
	xs := SupportedShells()
	out := make([]string, len(xs))
	for i, s := range xs {
		out[i] = string(s)
	}
	sort.Strings(out)
	return out
}

const (
	builtinCompletionCommandID           = "cli.builtin.completion"
	builtinCompletionListID              = "cli.builtin.completion.list"
	builtinCompletionGenerateID          = "cli.builtin.completion.generate"
	builtinCompletionGenerateShellArgID  = "cli.builtin.completion.generate.shell"
	builtinCompletionInstallID           = "cli.builtin.completion.install"
	builtinCompletionInstallShellArgID   = "cli.builtin.completion.install.shell"
	builtinCompletionUninstallID         = "cli.builtin.completion.uninstall"
	builtinCompletionUninstallShellArgID = "cli.builtin.completion.uninstall.shell"
	builtinCompletionStatusID            = "cli.builtin.completion.status"
	builtinCompletionStatusShellArgID    = "cli.builtin.completion.status.shell"
	builtinCompletionDoctorID            = "cli.builtin.completion.doctor"
	builtinCompletionDoctorShellArgID    = "cli.builtin.completion.doctor.shell"
)

func shellValue() Value {
	choices := make([]Choice, 0, len(SupportedShells()))
	for _, shell := range SupportedShells() {
		choices = append(choices, Choice{Value: string(shell)})
	}
	return EnumValue(choices...)
}

func builtinCompletionCommand() Command {
	return Command{
		ID: builtinCompletionCommandID, Name: "completion", Summary: "manage generated shell completions",
		Commands: []Command{
			{ID: builtinCompletionListID, Name: "list", Summary: "list supported shells"},
			{ID: builtinCompletionGenerateID, Name: "generate", Summary: "generate completion code", Args: []Arg{{ID: builtinCompletionGenerateShellArgID, Name: "shell", Summary: "target shell", Value: shellValue(), Required: true}}},
			{ID: builtinCompletionInstallID, Name: "install", Summary: "install generated completion", Args: []Arg{{ID: builtinCompletionInstallShellArgID, Name: "shell", Summary: "target shell; omit to install all", Value: shellValue()}}},
			{ID: builtinCompletionUninstallID, Name: "uninstall", Summary: "uninstall generated completion", Args: []Arg{{ID: builtinCompletionUninstallShellArgID, Name: "shell", Summary: "target shell; omit to uninstall all", Value: shellValue()}}},
			{ID: builtinCompletionStatusID, Name: "status", Summary: "show completion installation status", Args: []Arg{{ID: builtinCompletionStatusShellArgID, Name: "shell", Summary: "target shell; omit to show all", Value: shellValue()}}},
			{ID: builtinCompletionDoctorID, Name: "doctor", Summary: "diagnose completion installation", Args: []Arg{{ID: builtinCompletionDoctorShellArgID, Name: "shell", Summary: "target shell; omit to check all", Value: shellValue()}}},
		},
	}
}

func (c *CompiledApp) installCompletionHandlers() {
	c.handlers[builtinCompletionListID] = func(inv *Invocation) error {
		for _, name := range sortedShellNames() {
			if _, err := fmt.Fprintln(inv.IO.Out, name); err != nil {
				return err
			}
		}
		return nil
	}
	c.handlers[builtinCompletionGenerateID] = func(inv *Invocation) error {
		name, ok := ValueAs[string](inv, builtinCompletionGenerateShellArgID)
		if !ok {
			return &Diagnostic{Code: CodeMissingArgument, Kind: "usage", Message: "missing shell", Class: ExitUsage}
		}
		script, err := c.CompletionScript(Shell(name))
		if err != nil {
			return err
		}
		_, err = fmt.Fprint(inv.IO.Out, script)
		return err
	}
	c.handlers[builtinCompletionInstallID] = func(inv *Invocation) error {
		return c.installCompletions(inv, optionalCompletionShell(inv, builtinCompletionInstallShellArgID))
	}
	c.handlers[builtinCompletionUninstallID] = func(inv *Invocation) error {
		return c.uninstallCompletions(inv, optionalCompletionShell(inv, builtinCompletionUninstallShellArgID))
	}
	c.handlers[builtinCompletionStatusID] = func(inv *Invocation) error {
		return c.completionStatus(inv, optionalCompletionShell(inv, builtinCompletionStatusShellArgID))
	}
	c.handlers[builtinCompletionDoctorID] = func(inv *Invocation) error {
		return c.completionDoctor(inv, optionalCompletionShell(inv, builtinCompletionDoctorShellArgID))
	}
}
